# Generated by Django 2.2.7 on 2020-02-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_auto_20200211_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=350),
        ),
    ]
