# Generated by Django 2.2.7 on 2020-02-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_auto_20200211_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=120),
        ),
    ]
