# Generated by Django 2.2.7 on 2020-02-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_auto_20200214_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['timestamp']},
        ),
    ]
